language: python
python:
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
services:
- redis-server
- mongodb
- docker
install: pip install -r requirements.txt

env:
  global:
  - secure: lZKvS/zFwWELzcBD8+Yum57GHFb3+Ltc9hibLpecwHe826+llMQCCH5lkZSEXWvc5rVgW28zQN3RcYnmW9iaePQXD6SIhQlrZej5kkwPvPXMxbqzRrN9iVaFgyTJiSVsy5onZUkwY6ixPMrBfcy6VbcnSnnJHhOYyMDw56Y4jam0Lv3rykoaHls+D+NHREA51pEuBLNL6Y2XrEIlIZePr6FtFT/Pwg4H1fvkAHpM8IaCEISUFairwrN6KiBHX1pF9JOkEanMA7weuR+z7VC7sKWLIsrJ9rGHXjFVkiZYtm6f6unH71EK3xRR/MeuEdQrPNDJsnikqZPRuCCV8YfFycjoOEoyDNU7y5FRS3ZXQOBaObPGb/QLlI4PpX96kQHfE3fXMMJG+NDkTGk8uFDB1Il7LYXZDYlNUk8/RE9azOLwy9sR9+ZIRd7O09ZO9vpptR/mjqrOVFY5NVm3zDlArDofpyJVVrmOaA//SY4oEy+jACS3sEUEiGXYpLkKJQb75avncnzVPxG6NYpcNSjeFMaF17+YLF5S2DfrQ5iZtATV+ysnYrNbgi0cEmIbh1bRwrizMqkQyjB/mzBF0S+JazOJDa125ZQEbNw9ulBMsOGQ4zaYBn+K/Yznb6Xwsariroabvczey2Jc4jvY9166BA1ieFmJjkgYFYXenT/JLSQ=
  - secure: FoNQCY4CQDj7KQqD0ahwKVcyTjEC9kJytpAKxbgpwlfgPjUO4lNGVi0v7v09Dyr0yPeLlzNlqQmxt0NR80Hh+JNiRE+IVFeRHtLY3emH/6fPcFfCxRLLvgT9c3p4QeNHLz61SuqZ2/PHoWit20BHAosgFhCZ4rGqvOciPm6cJNbq4L2MA1PPzwpdFBuHWedNiMfF2FF1jnN3NFVbEurqqDGgDJz8rrYSu5HSu2qojSvPa2MF/nmAcDSdJw3rUeVytGlimytQ6rrf0ucxRVE7ynyWap4rBygDBzI/DZcs6zSwWhUCvQG66wwdGxnz9parAxGv7bZRUtL6IzE+QJnLY/bsjimusQ8WcE91onz74D/tX9pzJClO8woLyV75FHP/xi7I0UuETCWCRehwvkb/OS4657kBMj7xVApHOywJymRFKugKPiQKlPtbbKD+7Z4FczQ2qRfGHGnzLcv+UeQEO0R5fZuxBfG/BTXME73Qj/mzCq4LIrFezzQMSbCGQkBsmOvapzp8ClwEIwIVfQCCs+LrQlYvdf1PMxMTPXt2GCZoNUk8J3LG+U7anHJq0eHYRaW54iw61ipG031B+Jc/MoAgs0bU+SObnQk7rYyjEkOXcn+c018MLuZBwNnMGjo1ixc+vU4jEJt9S3qPDLQh0Knt3yI2idp7p5e1N1SCz80=

script: bash start.sh