language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
services:
- redis-server
- mongodb
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_ad8f1517fc45_key -iv $encrypted_ad8f1517fc45_iv
  -in .env.enc -out .env -d
install: pip install -r requirements.txt
script: timeout -sHUP 0.5m bash start.sh; if [ "$?" -eq 124 ]; then exit 0 ; else
  exit 1 ; fi
